### ISSUE TITLE
Unable to load skill

### ISSUE THREAD

**Issue by 5trongthany** [jamesmf/mycroft-mozilla-iot-skill#1]
Installed via custom skill installer, but nothing shows in `home.mycroft.ai`

Logs from `skills.log`

```
2020-09-08 23:57:15.619 | INFO     |   857 | mycroft.skills.__main__:_update_system_clock:104 | Updating the system clock via NTP...
2020-09-08 23:57:15.635 | INFO     |   857 | mycroft.enclosure.display_manager:_write_data:70 | Display Manager is creating /ramdisk/mycroft/ipc/managers/disp_info
2020-09-08 23:57:24.860 | INFO     |   857 | mycroft.skills.__main__:_update_device_attributes_on_backend:144 | Sending updated device attributes to the backend...
2020-09-08 23:57:24.893 | INFO     |   857 | mycroft.skills.settings:save_settings:111 | Skill settings successfully saved to /opt/mycroft/skills/mycroft-mark-1.mycroftai/settings.json
2020-09-08 23:57:25.094 | INFO     |   857 | mycroft.skills.__main__:on_ready:177 | Skill service is ready.
2020-09-08 23:57:25.118 | INFO     |   857 | mycroft.skills.skill_manager:_load_on_startup:270 | Loading installed skills...
2020-09-08 23:57:25.131 | INFO     |   857 | mycroft.skills.skill_loader:load:161 | ATTEMPTING TO LOAD SKILL: mycroft-spelling.mycroftai
2020-09-08 23:57:25.158 | INFO     |   857 | mycroft.skills.settings:get_local_settings:78 | /opt/mycroft/skills/mycroft-spelling.mycroftai/settings.json
2020-09-08 23:57:25.238 | INFO     |   857 | mycroft.skills.skill_loader:_communicate_load_status:320 | Skill mycroft-spelling.mycroftai loaded successfully
2020-09-08 23:57:25.246 | INFO     |   857 | mycroft.skills.skill_loader:load:161 | ATTEMPTING TO LOAD SKILL: mycroft-mozilla-iot-skill.jamesmf
2020-09-08 23:57:25.303 | INFO     |   857 | mycroft.skills.settings:get_local_settings:78 | /opt/mycroft/skills/mycroft-mozilla-iot-skill.jamesmf/settings.json
2020-09-08 23:57:25.367 | INFO     |   857 | MozillaIoTSkill | Removing all handlers...
2020-09-08 23:57:25.423 | ERROR    |   857 | mycroft.skills.skill_loader:_create_skill_instance:289 | Skill initialization failed with TypeError("'NoneType' object is not subscriptable")
Traceback (most recent call last):
  File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/mycroft/skills/skill_loader.py", line 283, in _create_skill_instance
    self.instance.initialize()
  File "/opt/mycroft/skills/mycroft-mozilla-iot-skill.jamesmf/__init__.py", line 143, in initialize
    self._setup()
  File "/opt/mycroft/skills/mycroft-mozilla-iot-skill.jamesmf/__init__.py", line 147, in _setup
    token=self.settings.get("token"), host=self.settings.get("host")
  File "/opt/mycroft/skills/mycroft-mozilla-iot-skill.jamesmf/__init__.py", line 61, in __init__
    if host[-1] == "/":
TypeError: 'NoneType' object is not subscriptable
2020-09-08 23:57:25.430 | ERROR    |   857 | mycroft.skills.skill_loader:_communicate_load_status:327 | Skill mycroft-mozilla-iot-skill.jamesmf failed to load
2020-09-08 23:57:25.434 | INFO     |   857 | mycroft.skills.skill_loader:load:161 | ATTEMPTING TO LOAD SKILL: mycroft-audio-record.mycroftai
2020-09-08 23:57:25.465 | INFO     |   857 | mycroft.skills.settings:get_local_settings:78 | /opt/mycroft/skills/mycroft-audio-record.mycroftai/settings.json
2020-09-08 23:57:25.567 | INFO     |   857 | mycroft.skills.skill_loader:_communicate_load_status:320 | Skill mycroft-audio-record.mycroftai loaded successfully
2020-09-08 23:57:25.572 | INFO     |   857 | mycroft.skills.skill_loader:load:161 | ATTEMPTING TO LOAD SKILL: mycroft-joke.mycroftai
2020-09-08 23:57:25.669 | INFO     |   857 | mycroft.skills.settings:get_local_settings:78 | /opt/mycroft/skills/mycroft-joke.mycroftai/settings.json
2020-09-08 23:57:25.836 | INFO     |   857 | mycroft.skills.skill_loader:_communicate_load_status:320 | Skill mycroft-joke.mycroftai loaded successfully
2020-09-08 23:57:25.846 | INFO     |   857 | mycroft.skills.skill_loader:load:161 | ATTEMPTING TO LOAD SKILL: game-zork.forslund
```

**Comment by jamesmf** [comment]
Sorry about that, it doesn't look like it works until you've been able to specify your settings. I will push a fix for that soon.

I suspect it would work if you manually edited your settings.json, but that is a pain

**Comment by jamesmf** [comment]
Okay sorry for the slow response - that should at the very least fix the issue you posted, but let me know if you encounter any more

**Comment by jamesmf** [comment]
Did you happen to see if the skill successfully registered your Things? It should print to the log a list of the Things it found when it starts up ( if it can connect to your gateway via the settings you provide)
